"use strict";
exports.__esModule = true;
exports.route = void 0;
var express_1 = require("express");
var auth_1 = require("../Authentication/auth");
var sign_1 = require("../Modules/login/controller/sign");
var create_1 = require("../Modules/users/controller/create");
var Create_1 = require("../Modules/deposites/controller/Create");
var getAll_1 = require("../Modules/deposites/controller/getAll");
var getByName_1 = require("../Modules/deposites/controller/getByName");
var deleteById_1 = require("../Modules/deposites/controller/deleteById");
var Create_2 = require("../Modules/withdraws/controller/Create");
var getAll_2 = require("../Modules/withdraws/controller/getAll");
var getByName_2 = require("../Modules/withdraws/controller/getByName");
var deleteById_2 = require("../Modules/withdraws/controller/deleteById");
var route = (0, express_1.Router)();
exports.route = route;
var createDeposites = new Create_1.DepositeCreate().create;
var getAllDeposites = new getAll_1.DepositeGetAll().getAll;
var getByNameDeposites = new getByName_1.DepositeGetByName().get;
var deleteDeposite = new deleteById_1.DeleteDepositeController().execute;
var createUser = new create_1.CreateUserController().create;
var login = new sign_1.SignController().execute;
var createWithdraw = new Create_2.WithdrawCreate().create;
var getAllWithdraw = new getAll_2.WithdrawGetAll().getAll;
var getByNameWithdraw = new getByName_2.WithdrawGetByName().get;
var deleteWithdraw = new deleteById_2.DeleteWithdrawController().execute;
route.post("/login", login);
route.post("/users", createUser);
route.post("/deposites", auth_1.Authentication, createDeposites);
route.get("/deposites", auth_1.Authentication, getAllDeposites);
route.get("/deposites/:name", auth_1.Authentication, getByNameDeposites);
route["delete"]("/deposites/:transactionId", auth_1.Authentication, deleteDeposite);
route.post("/withdraws", auth_1.Authentication, createWithdraw);
route.get("/withdraws", auth_1.Authentication, getAllWithdraw);
route.get("/withdraws/:name", auth_1.Authentication, getByNameWithdraw);
route["delete"]("/withdraws/:transactionId", auth_1.Authentication, deleteWithdraw);
